### PR TITLE
Bump version, update dependencies.

### PR DESCRIPTION
**Pull request by mrstegeman**
This will (finally) let the adapter build with Node 12.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Thanks for merging! Would you mind if I build a new release?

**Comment by matco** [comment]
Sure!

**Comment by matco** [comment]
I meant "go ahead". By the way, I will soon have time to test the version 0.11 of WebThings Gateway. Thanks for keeping this add-on up to date!

**Comment by mrstegeman** [comment]
No problem! I've merged the new version: https://github.com/mozilla-iot/addon-list/pull/736

**Pull request merged**
